---

- name: Get OPA route details for output
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: "{{ opa_name }}"
    namespace: "{{ namespace }}"
  register: opa_route

- name: Display OPA access information
  ansible.builtin.debug:
    msg:
      - "OPA has been deployed successfully!"
      - "You can access OPA at: https://{{ opa_route.resources[0].spec.host }}"
      - "Try the following command to test:"
      - "curl https://{{ opa_route.resources[0].spec.host }}/v1/data"
  when: opa_route.resources is defined and opa_route.resources | length > 0
