#SPDX-License-Identifier: MIT-0
---
# tasks file for opa

- name: Create OPA Deployment
  include_tasks: deployment.yml

- name: Create OPA Service
  include_tasks: service.yml

- name: Create OPA Route
  include_tasks: route.yml

- name: Wait for OPA deployment to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ opa_name }}"
    namespace: "{{ namespace }}"
  register: opa_deployment
  until: 
    - opa_deployment.resources is defined
    - opa_deployment.resources | length > 0
    - opa_deployment.resources[0].status.readyReplicas is defined
    - opa_deployment.resources[0].status.readyReplicas == opa_deployment.resources[0].status.replicas
  retries: 10
  delay: 10

- name: Load OPA policies
  include_tasks: load_policies.yml
  when: opa_policies | length > 0

- name: Display OPA access information
  include_tasks: access_info.yml
