---
# Task file for creating the OPA Route

- name: Create OPA Route with TLS
  kubernetes.core.k8s:
    state: present
    namespace: "{{ opa_namespace }}"
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ opa_name }}"
        namespace: "{{ opa_namespace }}"
        labels:
          app: "{{ opa_name }}"
      spec:
        to:
          kind: Service
          name: "{{ opa_name }}"
          weight: 100
        port:
          targetPort: http
        tls:
          termination: "edge"
          insecureEdgeTerminationPolicy: "Redirect"
        wildcardPolicy: None
