---
# Task file for creating the OPA Service

- name: Create OPA Service
  kubernetes.core.k8s:
    state: present
    namespace: "{{ opa_namespace }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ opa_name }}"
        namespace: "{{ opa_namespace }}"
        labels:
          app: "{{ opa_name }}"
      spec:
        ports:
          - name: http
            port: 8181
            targetPort: 8181
            protocol: TCP
        selector:
          app: "{{ opa_name }}"
        type: ClusterIP
        sessionAffinity: None
