#SPDX-License-Identifier: MIT-0
---
# defaults file for opa

opa_namespace: opa

opa_image: openpolicyagent/opa:latest
opa_name: opa
replicas: 1

cpu_request: 100m
cpu_limit: 500m
memory_request: 256Mi
memory_limit: 512Mi


# OPA policies to load from Git repository
opa_policies:
  - name: allowed_false
    url: "https://raw.githubusercontent.com/TheRealHaoLiu/example-opa-policy-for-aap/main/aap_policy_examples/allowed_false.rego"
  - name: extra_vars_validation
    url: "https://raw.githubusercontent.com/TheRealHaoLiu/example-opa-policy-for-aap/main/aap_policy_examples/extra_vars_validation.rego"
  - name: global_credential_allowed_false
    url: "https://raw.githubusercontent.com/TheRealHaoLiu/example-opa-policy-for-aap/main/aap_policy_examples/global_credential_allowed_false.rego"
  - name: maintenance_window
    url: "https://raw.githubusercontent.com/TheRealHaoLiu/example-opa-policy-for-aap/main/aap_policy_examples/maintenance_window.rego"
  - name: mismatch_prefix_allowed_false
    url: "https://raw.githubusercontent.com/TheRealHaoLiu/example-opa-policy-for-aap/main/aap_policy_examples/mismatch_prefix_allowed_false.rego"
  - name: superuser_allowed_false
    url: "https://raw.githubusercontent.com/TheRealHaoLiu/example-opa-policy-for-aap/main/aap_policy_examples/superuser_allowed_false.rego"
  - name: team_based_extra_vars_restriction
    url: "https://raw.githubusercontent.com/TheRealHaoLiu/example-opa-policy-for-aap/main/aap_policy_examples/team_based_extra_vars_restriction.rego"
  - name: jt_naming_validation
    url: "https://raw.githubusercontent.com/TheRealHaoLiu/example-opa-policy-for-aap/main/aap_policy_examples/jt_naming_validation.rego"

